import type { TrialSignalGateV2 } from "@workspace/api-client-react";

const collected = (value: number) => ({ status: "collected" as const, value });

const track = {
  status: "collected" as const,
  frame_count: collected(300),
  detected: collected(200),
  predicted: collected(50),
  lost: collected(50),
  detected_ratio: collected(2 / 3),
  predicted_ratio: collected(1 / 6),
  lost_ratio: collected(1 / 6),
  longest_lost_streak: collected(5),
  false_positive_island_count: collected(1),
  max_step_px: collected(20),
};

export const ACCEPTABLE_TRIAL_SIGNAL_GATE: TrialSignalGateV2 = {
  schema_version: "2.0",
  status: "acceptable",
  coverage_complete: true,
  evidence_available: true,
  trajectory_acceptable: true,
  signal_acceptable: true,
  acceptance_metrics_complete: true,
  acceptance_contract_complete: true,
  quality_acceptable: true,
  operator_confirmation_required: true,
  reason_codes: ["quality_thresholds_passed"],
  failure_classification: {
    code: "acceptable",
    severity: "none",
    summary: "The trial signal is acceptable.",
    recommended_action: "Review the bound visual evidence.",
  },
  threshold_profile: {
    profile_id: "test-profile",
    version: "1.1",
    algorithm_version: "trial-signal-gate-v2.1",
    matching_rules: {
      stage_counter_reconciliation:
        "all_required_counters_present_and_reconciled",
      track_metric_scope: "raw_and_cleaned_when_postprocess_enabled",
      follow_cam_scope: "motion_and_action_retention_when_enabled",
      required_visual_evidence: [
        "wide_context",
        "tight_crop",
        "follow_cam_when_enabled",
        "scale_strata",
        "lighting_strata",
        "attack_transition_windows",
      ],
      required_integrity: ["media_integrity", "identity_binding"],
      acceptance_contract: "server_verified_bundle_required",
    },
    sha256: "a".repeat(64),
    thresholds: {
      minimum_detected_ratio: 0.5,
      maximum_predicted_ratio: 0.35,
      maximum_lost_ratio: 0.25,
      maximum_longest_lost_streak: 30,
      maximum_false_positive_islands_per_100_frames: 8,
      maximum_suspicious_tracklet_ratio: 0.35,
      maximum_step_px: 600,
      maximum_follow_cam_pan_step_px: 90,
      maximum_follow_cam_pan_accel_px: 120,
      maximum_follow_cam_zoom_step_ratio: 0.1,
      maximum_ai_review_triggers_per_100_frames: 10,
      maximum_event_candidates_per_100_frames: 25,
    },
  },
  stage_counts: {
    schema_version: "2.0",
    coverage_status: "complete",
    evaluated_frames: { value: 300, status: "collected" },
    detected_frames: { value: 200, status: "collected" },
    predicted_frames: { value: 50, status: "collected" },
    lost_frames: { value: 50, status: "collected" },
    raw_candidates: { value: 240, status: "collected" },
    class_mapped_candidates: { value: 240, status: "collected" },
    filtered_candidates: { value: 220, status: "collected" },
    selected_candidates: { value: 200, status: "collected" },
    tracklets: { value: 3, status: "collected" },
    rejection_reasons: { confidence_below_min: 20 },
    reconciliation: { status: "reconciled", reason_codes: [] },
  },
  trajectory: { raw: { frame_count: 300 } },
  diagnostics: {
    raw_track: track,
    cleaned_track: track,
    rejection_reasons: {
      status: "collected",
      value: { confidence_below_min: 20 },
    },
    ai_review_trigger_count: collected(1),
    ai_review_triggers_per_100_frames: collected(1 / 3),
    event_candidate_count: collected(2),
    event_candidates_per_100_frames: collected(2 / 3),
    follow_cam: {
      status: "collected",
      max_pan_step_px: collected(20),
      max_pan_accel_px: collected(30),
      max_zoom_step_ratio: collected(0.02),
    },
  },
  evidence: {
    wide_context: "available",
    tight_crop: "available",
    follow_cam: "available",
    follow_cam_action_retention: "complete",
    scale_strata: "complete",
    lighting_strata: "complete",
    attack_transition_windows: "complete",
    media_integrity: "complete",
    identity_binding: "complete",
  },
};
