import path from "node:path";
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    include: [
      "src/**/*.vitest.test.{ts,tsx}",
      "src/lib/productionWorkflow.test.ts",
      "src/lib/fieldGeometry.test.ts",
      "src/lib/productionCalibration.test.ts",
      "src/lib/productionTrial.test.ts",
      "src/lib/productionDetectorProbe.test.ts",
      "src/lib/ballAnnotationGeometry.test.ts",
      "src/lib/productionBallAnnotation.test.ts",
      "src/lib/productionConfigFreeze.test.ts",
      "src/lib/productionBroadcast.test.ts",
      "src/lib/broadcastDelivery.test.ts",
      "src/lib/productionHistory.test.ts",
      "src/lib/productionCutover.test.ts",
      "src/components/production/**/*.test.tsx",
      "src/components/history/**/*.test.tsx",
      "src/pages/production.test.tsx",
      "src/App.vitest.test.tsx",
    ],
    coverage: {
      provider: "v8",
      reportsDirectory: path.resolve(
        import.meta.dirname,
        "../../tmp/coverage/web-production-workflow",
      ),
      include: [
        "src/lib/productionWorkflow.ts",
        "src/lib/fieldGeometry.ts",
        "src/lib/productionCalibration.ts",
        "src/lib/productionTrial.ts",
        "src/lib/productionDetectorProbe.ts",
        "src/lib/ballAnnotationGeometry.ts",
        "src/lib/productionBallAnnotation.ts",
        "src/lib/productionReviewProxyRepair.ts",
        "src/lib/productionConfigFreeze.ts",
        "src/lib/productionBroadcast.ts",
        "src/lib/broadcastDelivery.ts",
        "src/lib/productionHistory.ts",
        "src/components/broadcast/BroadcastReviewEvidenceStep.tsx",
        "src/components/broadcast/useBroadcastReviewEvidenceController.ts",
        "src/components/production/ProductionDetectorProbeController.tsx",
        "src/components/production/ProductionDetectorProbePanel.tsx",
        "src/components/production/BallAnnotationCanvas.tsx",
        "src/components/production/ProductionBallAnnotationController.tsx",
        "src/components/production/ProductionBallAnnotationPanel.tsx",
        "src/components/production/ProductionFeasibilityDashboard.tsx",
      ],
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        statements: 90,
        "src/components/broadcast/BroadcastReviewEvidenceStep.tsx": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/components/broadcast/useBroadcastReviewEvidenceController.ts": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/lib/productionHistory.ts": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/lib/productionDetectorProbe.ts": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/lib/ballAnnotationGeometry.ts": {
          branches: 95,
          functions: 95,
          lines: 95,
          statements: 95,
        },
        "src/lib/productionBallAnnotation.ts": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/lib/productionReviewProxyRepair.ts": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/components/production/ProductionDetectorProbeController.tsx": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/components/production/ProductionDetectorProbePanel.tsx": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/components/production/BallAnnotationCanvas.tsx": {
          branches: 80,
          functions: 80,
          lines: 80,
          statements: 80,
        },
        "src/components/production/ProductionBallAnnotationController.tsx": {
          branches: 90,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        "src/components/production/ProductionBallAnnotationPanel.tsx": {
          branches: 80,
          functions: 80,
          lines: 80,
          statements: 80,
        },
        "src/components/production/ProductionFeasibilityDashboard.tsx": {
          branches: 80,
          functions: 80,
          lines: 80,
          statements: 80,
        },
      },
    },
  },
});
